### ISSUE TITLE
Ampersands section repeats Abbreviations section.

### ISSUE THREAD

**Issue by andrewmcveigh** [uswitch/ustyle#166]
See below:

# Abbreviations

For names of companies or organisations, if an abbreviation is more familiar than the full form (e.g. BBC, IBM) use that. If not, write the name in full the first time you mention it, followed by the abbreviation in brackets. The next time you refer to it, use only the abbreviation.

# Ampersands (&)

For names of companies or organisations, if an abbreviation is more familiar than the full form (e.g. BBC, IBM) use that. If not, write the name in full the first time you mention it, followed by the abbreviation in brackets. The next time you refer to it, use only the abbreviation.

**Comment by thomasbritton** [comment]
This refers to this page: http://ustyle.guide/brand/language.html
