### ISSUE TITLE
Support AMP CSS requirements

### ISSUE THREAD

**Issue by annez** [uswitch/ustyle#196]
AMP doesn't support the `!important` flag, so to properly support AMP without writing a separate AMP stylesheet, we should consider the function of these:

https://github.com/uswitch/ustyle/blob/52899538495b70a18abfb32602a52dcbd4dc6766/vendor/assets/stylesheets/ustyle/login/_password-help.scss#L5

https://github.com/uswitch/ustyle/blob/52899538495b70a18abfb32602a52dcbd4dc6766/vendor/assets/stylesheets/ustyle/basics/_typography.scss#L119

https://github.com/uswitch/ustyle/blob/52899538495b70a18abfb32602a52dcbd4dc6766/vendor/assets/stylesheets/ustyle/icons/_base.scss#L230

https://github.com/uswitch/ustyle/blob/52899538495b70a18abfb32602a52dcbd4dc6766/vendor/assets/stylesheets/ustyle/tables/_tables-basic.scss#L21

https://github.com/uswitch/ustyle/blob/933b8bb9bf30c98160c68dad54e6c686acd90195/vendor/assets/stylesheets/ustyle/components/_tabs.scss#L194

Most of these can be amended by creating better specificity or may not need to be there at all in the first place.

**Comment by ivoreis** [comment]
I agree with that. I've encountered some issues with specificity a while ago using some of our utility classes. I've raised this discussion #197
