### ISSUE TITLE
Icon purge?

### ISSUE THREAD

**Issue by annez** [uswitch/ustyle#205]
We currently have quite a few unused icons in our repository. Would be good to purge ones we do not use.

Main reasons:

* SVGs are 327kb non-gzipped
* they are the biggest file being served on uSwitch, before the fonts.

If we come up with a better solution on doing the icons, then we should go with that.

**Comment by annez** [comment]
Unused icons:

- android
- angry
- apple
- arrow-up-left
- barchart
- blackberry
- book
- credit-card
- desktop
- doc
- github (only used in ustyle)
- happy
- laptop
- magnify-out
- neutral (only used in accounts hub test)
- power
- question
- sad
- tablet
- warning
- windows
- wondering
- world
- controller

**Comment by ricardomccerqueira** [comment]
I Agree with this, just probably need people to go through their verticals and make sure we don't need any of these.
From your list, I know in mobiles we need:

- android
- apple
- windows
- blackberry

I defend that stuff should only be in uStyle if it's shared, so if it's only used within mobiles, I'm very happy to cater for them myself

**Comment by annez** [comment]
@ricardomccerqueira Can you clarify that those are internal icons you are using are you are indeed using the ustyle icons?

**Comment by ricardomccerqueira** [comment]
mobiles-web is using a separate version of those Icons:
https://github.com/uswitch/mobiles-web/blob/master/app/assets/stylesheets/components/_svg-icons.sass#L70

Feel free to delete them from uStyle if you want.

**Comment by greenie** [comment]
@annez We don't use any of the icons that you mentioned in your second comment. We do use `--smiley` instead of `--happy` however.
