### ISSUE TITLE
jQuery an implicit dependency

### ISSUE THREAD

**Issue by annez** [uswitch/ustyle#235]
jQuery is currently needed to run:

* tabs.js
* overlay.js

We don't list it as a requirement, we probably should - or move away from jQuery.

**Comment by jpstevens** [comment]
As does `radioToggle.js`

**Comment by jpstevens** [comment]
Overlay requires a jQuery element as an input:

```
12:  overlay: $(".us-overlay-parent"),
```

Any project using this overlay will be using jQuery in order to send in the overlay element(s).

**Comment by annez** [comment]
This has been resolved.
